kafka:
  bootstrap-servers: 127.0.0.1:9092
  topic:
    teams : teams
    users: users
    teams-users : teams-users
    cafeteria : cafeteria


spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/where_are_you
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update