kafka:
  bootstrap-servers: 127.0.0.1:9092
  topic: members

spring:
  kafka:
    listener:
      concurrency: 2
    consumer:
      properties:
        heartbeat:
          interval:
            ms: 5000
