kafka:
  bootstrap-servers: 127.0.0.1:9092
  group:
    id:
      users: users
      teams: teams
      teams-users: teams-users
  topic:
    teams:
      create: teams-create
      update: teams-update
      delete: teams-delete
    users:
      create: users-create
      update: users-update
      delete: users-delete
    teams-users :
      create: teams-users-create
      update: teams-users-update
      delete: teams-users-delete
    cafeteria :
      create: cafeteria-create
      update: cafeteria-update
      delete: cafeteria-delete


spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/where_are_you
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

application:
  version: 21.39.0